#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentieImobiliara
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AgentieImobiliaraDB")]
	public partial class AgentieDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAnunturi_Vanzare(Anunturi_Vanzare instance);
    partial void UpdateAnunturi_Vanzare(Anunturi_Vanzare instance);
    partial void DeleteAnunturi_Vanzare(Anunturi_Vanzare instance);
    partial void InsertAnunturi_vizualizate(Anunturi_vizualizate instance);
    partial void UpdateAnunturi_vizualizate(Anunturi_vizualizate instance);
    partial void DeleteAnunturi_vizualizate(Anunturi_vizualizate instance);
    partial void InsertApartament(Apartament instance);
    partial void UpdateApartament(Apartament instance);
    partial void DeleteApartament(Apartament instance);
    partial void InsertCasa(Casa instance);
    partial void UpdateCasa(Casa instance);
    partial void DeleteCasa(Casa instance);
    partial void InsertLegaturaPrivatAgent(LegaturaPrivatAgent instance);
    partial void UpdateLegaturaPrivatAgent(LegaturaPrivatAgent instance);
    partial void DeleteLegaturaPrivatAgent(LegaturaPrivatAgent instance);
    partial void InsertProprietate(Proprietate instance);
    partial void UpdateProprietate(Proprietate instance);
    partial void DeleteProprietate(Proprietate instance);
    partial void InsertSpatiuComercial(SpatiuComercial instance);
    partial void UpdateSpatiuComercial(SpatiuComercial instance);
    partial void DeleteSpatiuComercial(SpatiuComercial instance);
    partial void InsertTeren(Teren instance);
    partial void UpdateTeren(Teren instance);
    partial void DeleteTeren(Teren instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertJudete(Judete instance);
    partial void UpdateJudete(Judete instance);
    partial void DeleteJudete(Judete instance);
    partial void InsertPrivat(Privat instance);
    partial void UpdatePrivat(Privat instance);
    partial void DeletePrivat(Privat instance);
    partial void InsertAgent(Agent instance);
    partial void UpdateAgent(Agent instance);
    partial void DeleteAgent(Agent instance);
    #endregion
		
		public AgentieDataContext() : 
				base(global::AgentieImobiliara.Properties.Settings.Default.AgentieImobiliaraDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AgentieDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AgentieDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AgentieDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AgentieDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Anunturi_Vanzare> Anunturi_Vanzares
		{
			get
			{
				return this.GetTable<Anunturi_Vanzare>();
			}
		}
		
		public System.Data.Linq.Table<Anunturi_vizualizate> Anunturi_vizualizates
		{
			get
			{
				return this.GetTable<Anunturi_vizualizate>();
			}
		}
		
		public System.Data.Linq.Table<Apartament> Apartaments
		{
			get
			{
				return this.GetTable<Apartament>();
			}
		}
		
		public System.Data.Linq.Table<Casa> Casas
		{
			get
			{
				return this.GetTable<Casa>();
			}
		}
		
		public System.Data.Linq.Table<LegaturaPrivatAgent> LegaturaPrivatAgents
		{
			get
			{
				return this.GetTable<LegaturaPrivatAgent>();
			}
		}
		
		public System.Data.Linq.Table<Proprietate> Proprietates
		{
			get
			{
				return this.GetTable<Proprietate>();
			}
		}
		
		public System.Data.Linq.Table<SpatiuComercial> SpatiuComercials
		{
			get
			{
				return this.GetTable<SpatiuComercial>();
			}
		}
		
		public System.Data.Linq.Table<Teren> Terens
		{
			get
			{
				return this.GetTable<Teren>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<Judete> Judetes
		{
			get
			{
				return this.GetTable<Judete>();
			}
		}
		
		public System.Data.Linq.Table<Privat> Privats
		{
			get
			{
				return this.GetTable<Privat>();
			}
		}
		
		public System.Data.Linq.Table<Agent> Agents
		{
			get
			{
				return this.GetTable<Agent>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Anunturi_Vanzare")]
	public partial class Anunturi_Vanzare : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AnuntID;
		
		private System.Nullable<int> _LegaturaID;
		
		private System.Nullable<System.DateTime> _DataPublicare;
		
		private System.Nullable<System.DateTime> _DataExpirare;
		
		private string _StatusAnunt;
		
		private EntitySet<Anunturi_vizualizate> _Anunturi_vizualizates;
		
		private EntityRef<LegaturaPrivatAgent> _LegaturaPrivatAgent;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAnuntIDChanging(int value);
    partial void OnAnuntIDChanged();
    partial void OnLegaturaIDChanging(System.Nullable<int> value);
    partial void OnLegaturaIDChanged();
    partial void OnDataPublicareChanging(System.Nullable<System.DateTime> value);
    partial void OnDataPublicareChanged();
    partial void OnDataExpirareChanging(System.Nullable<System.DateTime> value);
    partial void OnDataExpirareChanged();
    partial void OnStatusAnuntChanging(string value);
    partial void OnStatusAnuntChanged();
    #endregion
		
		public Anunturi_Vanzare()
		{
			this._Anunturi_vizualizates = new EntitySet<Anunturi_vizualizate>(new Action<Anunturi_vizualizate>(this.attach_Anunturi_vizualizates), new Action<Anunturi_vizualizate>(this.detach_Anunturi_vizualizates));
			this._LegaturaPrivatAgent = default(EntityRef<LegaturaPrivatAgent>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnuntID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AnuntID
		{
			get
			{
				return this._AnuntID;
			}
			set
			{
				if ((this._AnuntID != value))
				{
					this.OnAnuntIDChanging(value);
					this.SendPropertyChanging();
					this._AnuntID = value;
					this.SendPropertyChanged("AnuntID");
					this.OnAnuntIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LegaturaID", DbType="Int")]
		public System.Nullable<int> LegaturaID
		{
			get
			{
				return this._LegaturaID;
			}
			set
			{
				if ((this._LegaturaID != value))
				{
					if (this._LegaturaPrivatAgent.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLegaturaIDChanging(value);
					this.SendPropertyChanging();
					this._LegaturaID = value;
					this.SendPropertyChanged("LegaturaID");
					this.OnLegaturaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataPublicare", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataPublicare
		{
			get
			{
				return this._DataPublicare;
			}
			set
			{
				if ((this._DataPublicare != value))
				{
					this.OnDataPublicareChanging(value);
					this.SendPropertyChanging();
					this._DataPublicare = value;
					this.SendPropertyChanged("DataPublicare");
					this.OnDataPublicareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataExpirare", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataExpirare
		{
			get
			{
				return this._DataExpirare;
			}
			set
			{
				if ((this._DataExpirare != value))
				{
					this.OnDataExpirareChanging(value);
					this.SendPropertyChanging();
					this._DataExpirare = value;
					this.SendPropertyChanged("DataExpirare");
					this.OnDataExpirareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusAnunt", DbType="VarChar(20)")]
		public string StatusAnunt
		{
			get
			{
				return this._StatusAnunt;
			}
			set
			{
				if ((this._StatusAnunt != value))
				{
					this.OnStatusAnuntChanging(value);
					this.SendPropertyChanging();
					this._StatusAnunt = value;
					this.SendPropertyChanged("StatusAnunt");
					this.OnStatusAnuntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Anunturi_Vanzare_Anunturi_vizualizate", Storage="_Anunturi_vizualizates", ThisKey="AnuntID", OtherKey="AnuntID")]
		public EntitySet<Anunturi_vizualizate> Anunturi_vizualizates
		{
			get
			{
				return this._Anunturi_vizualizates;
			}
			set
			{
				this._Anunturi_vizualizates.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LegaturaPrivatAgent_Anunturi_Vanzare", Storage="_LegaturaPrivatAgent", ThisKey="LegaturaID", OtherKey="LegaturaID", IsForeignKey=true)]
		public LegaturaPrivatAgent LegaturaPrivatAgent
		{
			get
			{
				return this._LegaturaPrivatAgent.Entity;
			}
			set
			{
				LegaturaPrivatAgent previousValue = this._LegaturaPrivatAgent.Entity;
				if (((previousValue != value) 
							|| (this._LegaturaPrivatAgent.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LegaturaPrivatAgent.Entity = null;
						previousValue.Anunturi_Vanzares.Remove(this);
					}
					this._LegaturaPrivatAgent.Entity = value;
					if ((value != null))
					{
						value.Anunturi_Vanzares.Add(this);
						this._LegaturaID = value.LegaturaID;
					}
					else
					{
						this._LegaturaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("LegaturaPrivatAgent");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Anunturi_vizualizates(Anunturi_vizualizate entity)
		{
			this.SendPropertyChanging();
			entity.Anunturi_Vanzare = this;
		}
		
		private void detach_Anunturi_vizualizates(Anunturi_vizualizate entity)
		{
			this.SendPropertyChanging();
			entity.Anunturi_Vanzare = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Anunturi_vizualizate")]
	public partial class Anunturi_vizualizate : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _VizualizareID;
		
		private System.Nullable<int> _UtilizatorID;
		
		private System.Nullable<int> _AnuntID;
		
		private System.Nullable<System.DateTime> _DataVizualizare;
		
		private EntityRef<Anunturi_Vanzare> _Anunturi_Vanzare;
		
		private EntityRef<Privat> _Privat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVizualizareIDChanging(int value);
    partial void OnVizualizareIDChanged();
    partial void OnUtilizatorIDChanging(System.Nullable<int> value);
    partial void OnUtilizatorIDChanged();
    partial void OnAnuntIDChanging(System.Nullable<int> value);
    partial void OnAnuntIDChanged();
    partial void OnDataVizualizareChanging(System.Nullable<System.DateTime> value);
    partial void OnDataVizualizareChanged();
    #endregion
		
		public Anunturi_vizualizate()
		{
			this._Anunturi_Vanzare = default(EntityRef<Anunturi_Vanzare>);
			this._Privat = default(EntityRef<Privat>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VizualizareID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int VizualizareID
		{
			get
			{
				return this._VizualizareID;
			}
			set
			{
				if ((this._VizualizareID != value))
				{
					this.OnVizualizareIDChanging(value);
					this.SendPropertyChanging();
					this._VizualizareID = value;
					this.SendPropertyChanged("VizualizareID");
					this.OnVizualizareIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UtilizatorID", DbType="Int")]
		public System.Nullable<int> UtilizatorID
		{
			get
			{
				return this._UtilizatorID;
			}
			set
			{
				if ((this._UtilizatorID != value))
				{
					if (this._Privat.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUtilizatorIDChanging(value);
					this.SendPropertyChanging();
					this._UtilizatorID = value;
					this.SendPropertyChanged("UtilizatorID");
					this.OnUtilizatorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnuntID", DbType="Int")]
		public System.Nullable<int> AnuntID
		{
			get
			{
				return this._AnuntID;
			}
			set
			{
				if ((this._AnuntID != value))
				{
					if (this._Anunturi_Vanzare.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAnuntIDChanging(value);
					this.SendPropertyChanging();
					this._AnuntID = value;
					this.SendPropertyChanged("AnuntID");
					this.OnAnuntIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataVizualizare", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataVizualizare
		{
			get
			{
				return this._DataVizualizare;
			}
			set
			{
				if ((this._DataVizualizare != value))
				{
					this.OnDataVizualizareChanging(value);
					this.SendPropertyChanging();
					this._DataVizualizare = value;
					this.SendPropertyChanged("DataVizualizare");
					this.OnDataVizualizareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Anunturi_Vanzare_Anunturi_vizualizate", Storage="_Anunturi_Vanzare", ThisKey="AnuntID", OtherKey="AnuntID", IsForeignKey=true)]
		public Anunturi_Vanzare Anunturi_Vanzare
		{
			get
			{
				return this._Anunturi_Vanzare.Entity;
			}
			set
			{
				Anunturi_Vanzare previousValue = this._Anunturi_Vanzare.Entity;
				if (((previousValue != value) 
							|| (this._Anunturi_Vanzare.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Anunturi_Vanzare.Entity = null;
						previousValue.Anunturi_vizualizates.Remove(this);
					}
					this._Anunturi_Vanzare.Entity = value;
					if ((value != null))
					{
						value.Anunturi_vizualizates.Add(this);
						this._AnuntID = value.AnuntID;
					}
					else
					{
						this._AnuntID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Anunturi_Vanzare");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Privat_Anunturi_vizualizate", Storage="_Privat", ThisKey="UtilizatorID", OtherKey="PrivatID", IsForeignKey=true)]
		public Privat Privat
		{
			get
			{
				return this._Privat.Entity;
			}
			set
			{
				Privat previousValue = this._Privat.Entity;
				if (((previousValue != value) 
							|| (this._Privat.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Privat.Entity = null;
						previousValue.Anunturi_vizualizates.Remove(this);
					}
					this._Privat.Entity = value;
					if ((value != null))
					{
						value.Anunturi_vizualizates.Add(this);
						this._UtilizatorID = value.PrivatID;
					}
					else
					{
						this._UtilizatorID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Privat");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Apartament")]
	public partial class Apartament : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ApartamentID;
		
		private System.Nullable<int> _ProprietateID;
		
		private string _StadiuConstructie;
		
		private string _Compartimentare;
		
		private string _Mobilat_Utilat;
		
		private int _NrCamere;
		
		private System.Nullable<int> _NrBai;
		
		private System.Nullable<int> _Etaj;
		
		private System.Nullable<bool> _Parcare;
		
		private System.Nullable<bool> _Garaj;
		
		private System.Nullable<bool> _Curte;
		
		private System.Nullable<bool> _CentralaTermica;
		
		private System.Nullable<bool> _Balcon;
		
		private System.Nullable<bool> _Lift;
		
		private System.Nullable<bool> _Gradina;
		
		private System.Nullable<bool> _Terasa;
		
		private EntityRef<Proprietate> _Proprietate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnApartamentIDChanging(int value);
    partial void OnApartamentIDChanged();
    partial void OnProprietateIDChanging(System.Nullable<int> value);
    partial void OnProprietateIDChanged();
    partial void OnStadiuConstructieChanging(string value);
    partial void OnStadiuConstructieChanged();
    partial void OnCompartimentareChanging(string value);
    partial void OnCompartimentareChanged();
    partial void OnMobilat_UtilatChanging(string value);
    partial void OnMobilat_UtilatChanged();
    partial void OnNrCamereChanging(int value);
    partial void OnNrCamereChanged();
    partial void OnNrBaiChanging(System.Nullable<int> value);
    partial void OnNrBaiChanged();
    partial void OnEtajChanging(System.Nullable<int> value);
    partial void OnEtajChanged();
    partial void OnParcareChanging(System.Nullable<bool> value);
    partial void OnParcareChanged();
    partial void OnGarajChanging(System.Nullable<bool> value);
    partial void OnGarajChanged();
    partial void OnCurteChanging(System.Nullable<bool> value);
    partial void OnCurteChanged();
    partial void OnCentralaTermicaChanging(System.Nullable<bool> value);
    partial void OnCentralaTermicaChanged();
    partial void OnBalconChanging(System.Nullable<bool> value);
    partial void OnBalconChanged();
    partial void OnLiftChanging(System.Nullable<bool> value);
    partial void OnLiftChanged();
    partial void OnGradinaChanging(System.Nullable<bool> value);
    partial void OnGradinaChanged();
    partial void OnTerasaChanging(System.Nullable<bool> value);
    partial void OnTerasaChanged();
    #endregion
		
		public Apartament()
		{
			this._Proprietate = default(EntityRef<Proprietate>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApartamentID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ApartamentID
		{
			get
			{
				return this._ApartamentID;
			}
			set
			{
				if ((this._ApartamentID != value))
				{
					this.OnApartamentIDChanging(value);
					this.SendPropertyChanging();
					this._ApartamentID = value;
					this.SendPropertyChanged("ApartamentID");
					this.OnApartamentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProprietateID", DbType="Int")]
		public System.Nullable<int> ProprietateID
		{
			get
			{
				return this._ProprietateID;
			}
			set
			{
				if ((this._ProprietateID != value))
				{
					if (this._Proprietate.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProprietateIDChanging(value);
					this.SendPropertyChanging();
					this._ProprietateID = value;
					this.SendPropertyChanged("ProprietateID");
					this.OnProprietateIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StadiuConstructie", DbType="VarChar(20)")]
		public string StadiuConstructie
		{
			get
			{
				return this._StadiuConstructie;
			}
			set
			{
				if ((this._StadiuConstructie != value))
				{
					this.OnStadiuConstructieChanging(value);
					this.SendPropertyChanging();
					this._StadiuConstructie = value;
					this.SendPropertyChanged("StadiuConstructie");
					this.OnStadiuConstructieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Compartimentare", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Compartimentare
		{
			get
			{
				return this._Compartimentare;
			}
			set
			{
				if ((this._Compartimentare != value))
				{
					this.OnCompartimentareChanging(value);
					this.SendPropertyChanging();
					this._Compartimentare = value;
					this.SendPropertyChanged("Compartimentare");
					this.OnCompartimentareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobilat_Utilat", DbType="VarChar(20)")]
		public string Mobilat_Utilat
		{
			get
			{
				return this._Mobilat_Utilat;
			}
			set
			{
				if ((this._Mobilat_Utilat != value))
				{
					this.OnMobilat_UtilatChanging(value);
					this.SendPropertyChanging();
					this._Mobilat_Utilat = value;
					this.SendPropertyChanged("Mobilat_Utilat");
					this.OnMobilat_UtilatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NrCamere", DbType="Int NOT NULL")]
		public int NrCamere
		{
			get
			{
				return this._NrCamere;
			}
			set
			{
				if ((this._NrCamere != value))
				{
					this.OnNrCamereChanging(value);
					this.SendPropertyChanging();
					this._NrCamere = value;
					this.SendPropertyChanged("NrCamere");
					this.OnNrCamereChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NrBai", DbType="Int")]
		public System.Nullable<int> NrBai
		{
			get
			{
				return this._NrBai;
			}
			set
			{
				if ((this._NrBai != value))
				{
					this.OnNrBaiChanging(value);
					this.SendPropertyChanging();
					this._NrBai = value;
					this.SendPropertyChanged("NrBai");
					this.OnNrBaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etaj", DbType="Int")]
		public System.Nullable<int> Etaj
		{
			get
			{
				return this._Etaj;
			}
			set
			{
				if ((this._Etaj != value))
				{
					this.OnEtajChanging(value);
					this.SendPropertyChanging();
					this._Etaj = value;
					this.SendPropertyChanged("Etaj");
					this.OnEtajChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parcare", DbType="Bit")]
		public System.Nullable<bool> Parcare
		{
			get
			{
				return this._Parcare;
			}
			set
			{
				if ((this._Parcare != value))
				{
					this.OnParcareChanging(value);
					this.SendPropertyChanging();
					this._Parcare = value;
					this.SendPropertyChanged("Parcare");
					this.OnParcareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Garaj", DbType="Bit")]
		public System.Nullable<bool> Garaj
		{
			get
			{
				return this._Garaj;
			}
			set
			{
				if ((this._Garaj != value))
				{
					this.OnGarajChanging(value);
					this.SendPropertyChanging();
					this._Garaj = value;
					this.SendPropertyChanged("Garaj");
					this.OnGarajChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Curte", DbType="Bit")]
		public System.Nullable<bool> Curte
		{
			get
			{
				return this._Curte;
			}
			set
			{
				if ((this._Curte != value))
				{
					this.OnCurteChanging(value);
					this.SendPropertyChanging();
					this._Curte = value;
					this.SendPropertyChanged("Curte");
					this.OnCurteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CentralaTermica", DbType="Bit")]
		public System.Nullable<bool> CentralaTermica
		{
			get
			{
				return this._CentralaTermica;
			}
			set
			{
				if ((this._CentralaTermica != value))
				{
					this.OnCentralaTermicaChanging(value);
					this.SendPropertyChanging();
					this._CentralaTermica = value;
					this.SendPropertyChanged("CentralaTermica");
					this.OnCentralaTermicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balcon", DbType="Bit")]
		public System.Nullable<bool> Balcon
		{
			get
			{
				return this._Balcon;
			}
			set
			{
				if ((this._Balcon != value))
				{
					this.OnBalconChanging(value);
					this.SendPropertyChanging();
					this._Balcon = value;
					this.SendPropertyChanged("Balcon");
					this.OnBalconChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lift", DbType="Bit")]
		public System.Nullable<bool> Lift
		{
			get
			{
				return this._Lift;
			}
			set
			{
				if ((this._Lift != value))
				{
					this.OnLiftChanging(value);
					this.SendPropertyChanging();
					this._Lift = value;
					this.SendPropertyChanged("Lift");
					this.OnLiftChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gradina", DbType="Bit")]
		public System.Nullable<bool> Gradina
		{
			get
			{
				return this._Gradina;
			}
			set
			{
				if ((this._Gradina != value))
				{
					this.OnGradinaChanging(value);
					this.SendPropertyChanging();
					this._Gradina = value;
					this.SendPropertyChanged("Gradina");
					this.OnGradinaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Terasa", DbType="Bit")]
		public System.Nullable<bool> Terasa
		{
			get
			{
				return this._Terasa;
			}
			set
			{
				if ((this._Terasa != value))
				{
					this.OnTerasaChanging(value);
					this.SendPropertyChanging();
					this._Terasa = value;
					this.SendPropertyChanged("Terasa");
					this.OnTerasaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proprietate_Apartament", Storage="_Proprietate", ThisKey="ProprietateID", OtherKey="ProprietateID", IsForeignKey=true, DeleteRule="CASCADE")]
		public Proprietate Proprietate
		{
			get
			{
				return this._Proprietate.Entity;
			}
			set
			{
				Proprietate previousValue = this._Proprietate.Entity;
				if (((previousValue != value) 
							|| (this._Proprietate.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Proprietate.Entity = null;
						previousValue.Apartaments.Remove(this);
					}
					this._Proprietate.Entity = value;
					if ((value != null))
					{
						value.Apartaments.Add(this);
						this._ProprietateID = value.ProprietateID;
					}
					else
					{
						this._ProprietateID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Proprietate");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Casa")]
	public partial class Casa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CasaID;
		
		private System.Nullable<int> _ProprietateID;
		
		private string _StadiuConstructie;
		
		private string _Mobilat_Utilat;
		
		private int _NrCamere;
		
		private System.Nullable<int> _NrBai;
		
		private System.Nullable<int> _NrEtaje;
		
		private System.Nullable<bool> _Parcare;
		
		private System.Nullable<bool> _Garaj;
		
		private System.Nullable<bool> _Curte;
		
		private System.Nullable<bool> _CentralaTermica;
		
		private System.Nullable<bool> _Gradina;
		
		private System.Nullable<bool> _Piscina;
		
		private System.Nullable<bool> _Canalizare;
		
		private EntityRef<Proprietate> _Proprietate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCasaIDChanging(int value);
    partial void OnCasaIDChanged();
    partial void OnProprietateIDChanging(System.Nullable<int> value);
    partial void OnProprietateIDChanged();
    partial void OnStadiuConstructieChanging(string value);
    partial void OnStadiuConstructieChanged();
    partial void OnMobilat_UtilatChanging(string value);
    partial void OnMobilat_UtilatChanged();
    partial void OnNrCamereChanging(int value);
    partial void OnNrCamereChanged();
    partial void OnNrBaiChanging(System.Nullable<int> value);
    partial void OnNrBaiChanged();
    partial void OnNrEtajeChanging(System.Nullable<int> value);
    partial void OnNrEtajeChanged();
    partial void OnParcareChanging(System.Nullable<bool> value);
    partial void OnParcareChanged();
    partial void OnGarajChanging(System.Nullable<bool> value);
    partial void OnGarajChanged();
    partial void OnCurteChanging(System.Nullable<bool> value);
    partial void OnCurteChanged();
    partial void OnCentralaTermicaChanging(System.Nullable<bool> value);
    partial void OnCentralaTermicaChanged();
    partial void OnGradinaChanging(System.Nullable<bool> value);
    partial void OnGradinaChanged();
    partial void OnPiscinaChanging(System.Nullable<bool> value);
    partial void OnPiscinaChanged();
    partial void OnCanalizareChanging(System.Nullable<bool> value);
    partial void OnCanalizareChanged();
    #endregion
		
		public Casa()
		{
			this._Proprietate = default(EntityRef<Proprietate>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CasaID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CasaID
		{
			get
			{
				return this._CasaID;
			}
			set
			{
				if ((this._CasaID != value))
				{
					this.OnCasaIDChanging(value);
					this.SendPropertyChanging();
					this._CasaID = value;
					this.SendPropertyChanged("CasaID");
					this.OnCasaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProprietateID", DbType="Int")]
		public System.Nullable<int> ProprietateID
		{
			get
			{
				return this._ProprietateID;
			}
			set
			{
				if ((this._ProprietateID != value))
				{
					if (this._Proprietate.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProprietateIDChanging(value);
					this.SendPropertyChanging();
					this._ProprietateID = value;
					this.SendPropertyChanged("ProprietateID");
					this.OnProprietateIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StadiuConstructie", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string StadiuConstructie
		{
			get
			{
				return this._StadiuConstructie;
			}
			set
			{
				if ((this._StadiuConstructie != value))
				{
					this.OnStadiuConstructieChanging(value);
					this.SendPropertyChanging();
					this._StadiuConstructie = value;
					this.SendPropertyChanged("StadiuConstructie");
					this.OnStadiuConstructieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobilat_Utilat", DbType="VarChar(20)")]
		public string Mobilat_Utilat
		{
			get
			{
				return this._Mobilat_Utilat;
			}
			set
			{
				if ((this._Mobilat_Utilat != value))
				{
					this.OnMobilat_UtilatChanging(value);
					this.SendPropertyChanging();
					this._Mobilat_Utilat = value;
					this.SendPropertyChanged("Mobilat_Utilat");
					this.OnMobilat_UtilatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NrCamere", DbType="Int NOT NULL")]
		public int NrCamere
		{
			get
			{
				return this._NrCamere;
			}
			set
			{
				if ((this._NrCamere != value))
				{
					this.OnNrCamereChanging(value);
					this.SendPropertyChanging();
					this._NrCamere = value;
					this.SendPropertyChanged("NrCamere");
					this.OnNrCamereChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NrBai", DbType="Int")]
		public System.Nullable<int> NrBai
		{
			get
			{
				return this._NrBai;
			}
			set
			{
				if ((this._NrBai != value))
				{
					this.OnNrBaiChanging(value);
					this.SendPropertyChanging();
					this._NrBai = value;
					this.SendPropertyChanged("NrBai");
					this.OnNrBaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NrEtaje", DbType="Int")]
		public System.Nullable<int> NrEtaje
		{
			get
			{
				return this._NrEtaje;
			}
			set
			{
				if ((this._NrEtaje != value))
				{
					this.OnNrEtajeChanging(value);
					this.SendPropertyChanging();
					this._NrEtaje = value;
					this.SendPropertyChanged("NrEtaje");
					this.OnNrEtajeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parcare", DbType="Bit")]
		public System.Nullable<bool> Parcare
		{
			get
			{
				return this._Parcare;
			}
			set
			{
				if ((this._Parcare != value))
				{
					this.OnParcareChanging(value);
					this.SendPropertyChanging();
					this._Parcare = value;
					this.SendPropertyChanged("Parcare");
					this.OnParcareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Garaj", DbType="Bit")]
		public System.Nullable<bool> Garaj
		{
			get
			{
				return this._Garaj;
			}
			set
			{
				if ((this._Garaj != value))
				{
					this.OnGarajChanging(value);
					this.SendPropertyChanging();
					this._Garaj = value;
					this.SendPropertyChanged("Garaj");
					this.OnGarajChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Curte", DbType="Bit")]
		public System.Nullable<bool> Curte
		{
			get
			{
				return this._Curte;
			}
			set
			{
				if ((this._Curte != value))
				{
					this.OnCurteChanging(value);
					this.SendPropertyChanging();
					this._Curte = value;
					this.SendPropertyChanged("Curte");
					this.OnCurteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CentralaTermica", DbType="Bit")]
		public System.Nullable<bool> CentralaTermica
		{
			get
			{
				return this._CentralaTermica;
			}
			set
			{
				if ((this._CentralaTermica != value))
				{
					this.OnCentralaTermicaChanging(value);
					this.SendPropertyChanging();
					this._CentralaTermica = value;
					this.SendPropertyChanged("CentralaTermica");
					this.OnCentralaTermicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gradina", DbType="Bit")]
		public System.Nullable<bool> Gradina
		{
			get
			{
				return this._Gradina;
			}
			set
			{
				if ((this._Gradina != value))
				{
					this.OnGradinaChanging(value);
					this.SendPropertyChanging();
					this._Gradina = value;
					this.SendPropertyChanged("Gradina");
					this.OnGradinaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Piscina", DbType="Bit")]
		public System.Nullable<bool> Piscina
		{
			get
			{
				return this._Piscina;
			}
			set
			{
				if ((this._Piscina != value))
				{
					this.OnPiscinaChanging(value);
					this.SendPropertyChanging();
					this._Piscina = value;
					this.SendPropertyChanged("Piscina");
					this.OnPiscinaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Canalizare", DbType="Bit")]
		public System.Nullable<bool> Canalizare
		{
			get
			{
				return this._Canalizare;
			}
			set
			{
				if ((this._Canalizare != value))
				{
					this.OnCanalizareChanging(value);
					this.SendPropertyChanging();
					this._Canalizare = value;
					this.SendPropertyChanged("Canalizare");
					this.OnCanalizareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proprietate_Casa", Storage="_Proprietate", ThisKey="ProprietateID", OtherKey="ProprietateID", IsForeignKey=true, DeleteRule="CASCADE")]
		public Proprietate Proprietate
		{
			get
			{
				return this._Proprietate.Entity;
			}
			set
			{
				Proprietate previousValue = this._Proprietate.Entity;
				if (((previousValue != value) 
							|| (this._Proprietate.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Proprietate.Entity = null;
						previousValue.Casas.Remove(this);
					}
					this._Proprietate.Entity = value;
					if ((value != null))
					{
						value.Casas.Add(this);
						this._ProprietateID = value.ProprietateID;
					}
					else
					{
						this._ProprietateID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Proprietate");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LegaturaPrivatAgent")]
	public partial class LegaturaPrivatAgent : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LegaturaID;
		
		private System.Nullable<int> _PrivatID;
		
		private System.Nullable<int> _ProprietateID;
		
		private System.Nullable<int> _AgentID;
		
		private string _TipVanzare;
		
		private EntitySet<Anunturi_Vanzare> _Anunturi_Vanzares;
		
		private EntityRef<Proprietate> _Proprietate;
		
		private EntityRef<Privat> _Privat;
		
		private EntityRef<Agent> _Agent;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLegaturaIDChanging(int value);
    partial void OnLegaturaIDChanged();
    partial void OnPrivatIDChanging(System.Nullable<int> value);
    partial void OnPrivatIDChanged();
    partial void OnProprietateIDChanging(System.Nullable<int> value);
    partial void OnProprietateIDChanged();
    partial void OnAgentIDChanging(System.Nullable<int> value);
    partial void OnAgentIDChanged();
    partial void OnTipVanzareChanging(string value);
    partial void OnTipVanzareChanged();
    #endregion
		
		public LegaturaPrivatAgent()
		{
			this._Anunturi_Vanzares = new EntitySet<Anunturi_Vanzare>(new Action<Anunturi_Vanzare>(this.attach_Anunturi_Vanzares), new Action<Anunturi_Vanzare>(this.detach_Anunturi_Vanzares));
			this._Proprietate = default(EntityRef<Proprietate>);
			this._Privat = default(EntityRef<Privat>);
			this._Agent = default(EntityRef<Agent>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LegaturaID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LegaturaID
		{
			get
			{
				return this._LegaturaID;
			}
			set
			{
				if ((this._LegaturaID != value))
				{
					this.OnLegaturaIDChanging(value);
					this.SendPropertyChanging();
					this._LegaturaID = value;
					this.SendPropertyChanged("LegaturaID");
					this.OnLegaturaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrivatID", DbType="Int")]
		public System.Nullable<int> PrivatID
		{
			get
			{
				return this._PrivatID;
			}
			set
			{
				if ((this._PrivatID != value))
				{
					if (this._Privat.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPrivatIDChanging(value);
					this.SendPropertyChanging();
					this._PrivatID = value;
					this.SendPropertyChanged("PrivatID");
					this.OnPrivatIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProprietateID", DbType="Int")]
		public System.Nullable<int> ProprietateID
		{
			get
			{
				return this._ProprietateID;
			}
			set
			{
				if ((this._ProprietateID != value))
				{
					if (this._Proprietate.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProprietateIDChanging(value);
					this.SendPropertyChanging();
					this._ProprietateID = value;
					this.SendPropertyChanged("ProprietateID");
					this.OnProprietateIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgentID", DbType="Int")]
		public System.Nullable<int> AgentID
		{
			get
			{
				return this._AgentID;
			}
			set
			{
				if ((this._AgentID != value))
				{
					if (this._Agent.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAgentIDChanging(value);
					this.SendPropertyChanging();
					this._AgentID = value;
					this.SendPropertyChanged("AgentID");
					this.OnAgentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipVanzare", DbType="VarChar(20)")]
		public string TipVanzare
		{
			get
			{
				return this._TipVanzare;
			}
			set
			{
				if ((this._TipVanzare != value))
				{
					this.OnTipVanzareChanging(value);
					this.SendPropertyChanging();
					this._TipVanzare = value;
					this.SendPropertyChanged("TipVanzare");
					this.OnTipVanzareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LegaturaPrivatAgent_Anunturi_Vanzare", Storage="_Anunturi_Vanzares", ThisKey="LegaturaID", OtherKey="LegaturaID")]
		public EntitySet<Anunturi_Vanzare> Anunturi_Vanzares
		{
			get
			{
				return this._Anunturi_Vanzares;
			}
			set
			{
				this._Anunturi_Vanzares.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proprietate_LegaturaPrivatAgent", Storage="_Proprietate", ThisKey="ProprietateID", OtherKey="ProprietateID", IsForeignKey=true, DeleteRule="CASCADE")]
		public Proprietate Proprietate
		{
			get
			{
				return this._Proprietate.Entity;
			}
			set
			{
				Proprietate previousValue = this._Proprietate.Entity;
				if (((previousValue != value) 
							|| (this._Proprietate.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Proprietate.Entity = null;
						previousValue.LegaturaPrivatAgents.Remove(this);
					}
					this._Proprietate.Entity = value;
					if ((value != null))
					{
						value.LegaturaPrivatAgents.Add(this);
						this._ProprietateID = value.ProprietateID;
					}
					else
					{
						this._ProprietateID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Proprietate");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Privat_LegaturaPrivatAgent", Storage="_Privat", ThisKey="PrivatID", OtherKey="PrivatID", IsForeignKey=true, DeleteRule="CASCADE")]
		public Privat Privat
		{
			get
			{
				return this._Privat.Entity;
			}
			set
			{
				Privat previousValue = this._Privat.Entity;
				if (((previousValue != value) 
							|| (this._Privat.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Privat.Entity = null;
						previousValue.LegaturaPrivatAgents.Remove(this);
					}
					this._Privat.Entity = value;
					if ((value != null))
					{
						value.LegaturaPrivatAgents.Add(this);
						this._PrivatID = value.PrivatID;
					}
					else
					{
						this._PrivatID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Privat");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Agent_LegaturaPrivatAgent", Storage="_Agent", ThisKey="AgentID", OtherKey="AgentID", IsForeignKey=true, DeleteRule="CASCADE")]
		public Agent Agent
		{
			get
			{
				return this._Agent.Entity;
			}
			set
			{
				Agent previousValue = this._Agent.Entity;
				if (((previousValue != value) 
							|| (this._Agent.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Agent.Entity = null;
						previousValue.LegaturaPrivatAgents.Remove(this);
					}
					this._Agent.Entity = value;
					if ((value != null))
					{
						value.LegaturaPrivatAgents.Add(this);
						this._AgentID = value.AgentID;
					}
					else
					{
						this._AgentID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Agent");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Anunturi_Vanzares(Anunturi_Vanzare entity)
		{
			this.SendPropertyChanging();
			entity.LegaturaPrivatAgent = this;
		}
		
		private void detach_Anunturi_Vanzares(Anunturi_Vanzare entity)
		{
			this.SendPropertyChanging();
			entity.LegaturaPrivatAgent = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Proprietate")]
	public partial class Proprietate : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProprietateID;
		
		private string _TipProprietate;
		
		private string _Inchiriere_Vanzare;
		
		private string _Denumire;
		
		private string _Descriere;
		
		private string _Localitate;
		
		private string _Judet;
		
		private double _Pret;
		
		private decimal _Suprafata;
		
		private string _Moneda;
		
		private EntitySet<Apartament> _Apartaments;
		
		private EntitySet<Casa> _Casas;
		
		private EntitySet<LegaturaPrivatAgent> _LegaturaPrivatAgents;
		
		private EntitySet<SpatiuComercial> _SpatiuComercials;
		
		private EntitySet<Teren> _Terens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProprietateIDChanging(int value);
    partial void OnProprietateIDChanged();
    partial void OnTipProprietateChanging(string value);
    partial void OnTipProprietateChanged();
    partial void OnInchiriere_VanzareChanging(string value);
    partial void OnInchiriere_VanzareChanged();
    partial void OnDenumireChanging(string value);
    partial void OnDenumireChanged();
    partial void OnDescriereChanging(string value);
    partial void OnDescriereChanged();
    partial void OnLocalitateChanging(string value);
    partial void OnLocalitateChanged();
    partial void OnJudetChanging(string value);
    partial void OnJudetChanged();
    partial void OnPretChanging(double value);
    partial void OnPretChanged();
    partial void OnSuprafataChanging(decimal value);
    partial void OnSuprafataChanged();
    partial void OnMonedaChanging(string value);
    partial void OnMonedaChanged();
    #endregion
		
		public Proprietate()
		{
			this._Apartaments = new EntitySet<Apartament>(new Action<Apartament>(this.attach_Apartaments), new Action<Apartament>(this.detach_Apartaments));
			this._Casas = new EntitySet<Casa>(new Action<Casa>(this.attach_Casas), new Action<Casa>(this.detach_Casas));
			this._LegaturaPrivatAgents = new EntitySet<LegaturaPrivatAgent>(new Action<LegaturaPrivatAgent>(this.attach_LegaturaPrivatAgents), new Action<LegaturaPrivatAgent>(this.detach_LegaturaPrivatAgents));
			this._SpatiuComercials = new EntitySet<SpatiuComercial>(new Action<SpatiuComercial>(this.attach_SpatiuComercials), new Action<SpatiuComercial>(this.detach_SpatiuComercials));
			this._Terens = new EntitySet<Teren>(new Action<Teren>(this.attach_Terens), new Action<Teren>(this.detach_Terens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProprietateID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProprietateID
		{
			get
			{
				return this._ProprietateID;
			}
			set
			{
				if ((this._ProprietateID != value))
				{
					this.OnProprietateIDChanging(value);
					this.SendPropertyChanging();
					this._ProprietateID = value;
					this.SendPropertyChanged("ProprietateID");
					this.OnProprietateIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipProprietate", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string TipProprietate
		{
			get
			{
				return this._TipProprietate;
			}
			set
			{
				if ((this._TipProprietate != value))
				{
					this.OnTipProprietateChanging(value);
					this.SendPropertyChanging();
					this._TipProprietate = value;
					this.SendPropertyChanged("TipProprietate");
					this.OnTipProprietateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inchiriere_Vanzare", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Inchiriere_Vanzare
		{
			get
			{
				return this._Inchiriere_Vanzare;
			}
			set
			{
				if ((this._Inchiriere_Vanzare != value))
				{
					this.OnInchiriere_VanzareChanging(value);
					this.SendPropertyChanging();
					this._Inchiriere_Vanzare = value;
					this.SendPropertyChanged("Inchiriere_Vanzare");
					this.OnInchiriere_VanzareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Denumire", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Denumire
		{
			get
			{
				return this._Denumire;
			}
			set
			{
				if ((this._Denumire != value))
				{
					this.OnDenumireChanging(value);
					this.SendPropertyChanging();
					this._Denumire = value;
					this.SendPropertyChanged("Denumire");
					this.OnDenumireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descriere", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Descriere
		{
			get
			{
				return this._Descriere;
			}
			set
			{
				if ((this._Descriere != value))
				{
					this.OnDescriereChanging(value);
					this.SendPropertyChanging();
					this._Descriere = value;
					this.SendPropertyChanged("Descriere");
					this.OnDescriereChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Localitate", DbType="VarChar(50)")]
		public string Localitate
		{
			get
			{
				return this._Localitate;
			}
			set
			{
				if ((this._Localitate != value))
				{
					this.OnLocalitateChanging(value);
					this.SendPropertyChanging();
					this._Localitate = value;
					this.SendPropertyChanged("Localitate");
					this.OnLocalitateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Judet", DbType="VarChar(50)")]
		public string Judet
		{
			get
			{
				return this._Judet;
			}
			set
			{
				if ((this._Judet != value))
				{
					this.OnJudetChanging(value);
					this.SendPropertyChanging();
					this._Judet = value;
					this.SendPropertyChanged("Judet");
					this.OnJudetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pret", DbType="Float NOT NULL")]
		public double Pret
		{
			get
			{
				return this._Pret;
			}
			set
			{
				if ((this._Pret != value))
				{
					this.OnPretChanging(value);
					this.SendPropertyChanging();
					this._Pret = value;
					this.SendPropertyChanged("Pret");
					this.OnPretChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Suprafata", DbType="Decimal(7,2) NOT NULL")]
		public decimal Suprafata
		{
			get
			{
				return this._Suprafata;
			}
			set
			{
				if ((this._Suprafata != value))
				{
					this.OnSuprafataChanging(value);
					this.SendPropertyChanging();
					this._Suprafata = value;
					this.SendPropertyChanged("Suprafata");
					this.OnSuprafataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Moneda", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Moneda
		{
			get
			{
				return this._Moneda;
			}
			set
			{
				if ((this._Moneda != value))
				{
					this.OnMonedaChanging(value);
					this.SendPropertyChanging();
					this._Moneda = value;
					this.SendPropertyChanged("Moneda");
					this.OnMonedaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proprietate_Apartament", Storage="_Apartaments", ThisKey="ProprietateID", OtherKey="ProprietateID")]
		public EntitySet<Apartament> Apartaments
		{
			get
			{
				return this._Apartaments;
			}
			set
			{
				this._Apartaments.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proprietate_Casa", Storage="_Casas", ThisKey="ProprietateID", OtherKey="ProprietateID")]
		public EntitySet<Casa> Casas
		{
			get
			{
				return this._Casas;
			}
			set
			{
				this._Casas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proprietate_LegaturaPrivatAgent", Storage="_LegaturaPrivatAgents", ThisKey="ProprietateID", OtherKey="ProprietateID")]
		public EntitySet<LegaturaPrivatAgent> LegaturaPrivatAgents
		{
			get
			{
				return this._LegaturaPrivatAgents;
			}
			set
			{
				this._LegaturaPrivatAgents.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proprietate_SpatiuComercial", Storage="_SpatiuComercials", ThisKey="ProprietateID", OtherKey="ProprietateID")]
		public EntitySet<SpatiuComercial> SpatiuComercials
		{
			get
			{
				return this._SpatiuComercials;
			}
			set
			{
				this._SpatiuComercials.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proprietate_Teren", Storage="_Terens", ThisKey="ProprietateID", OtherKey="ProprietateID")]
		public EntitySet<Teren> Terens
		{
			get
			{
				return this._Terens;
			}
			set
			{
				this._Terens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Apartaments(Apartament entity)
		{
			this.SendPropertyChanging();
			entity.Proprietate = this;
		}
		
		private void detach_Apartaments(Apartament entity)
		{
			this.SendPropertyChanging();
			entity.Proprietate = null;
		}
		
		private void attach_Casas(Casa entity)
		{
			this.SendPropertyChanging();
			entity.Proprietate = this;
		}
		
		private void detach_Casas(Casa entity)
		{
			this.SendPropertyChanging();
			entity.Proprietate = null;
		}
		
		private void attach_LegaturaPrivatAgents(LegaturaPrivatAgent entity)
		{
			this.SendPropertyChanging();
			entity.Proprietate = this;
		}
		
		private void detach_LegaturaPrivatAgents(LegaturaPrivatAgent entity)
		{
			this.SendPropertyChanging();
			entity.Proprietate = null;
		}
		
		private void attach_SpatiuComercials(SpatiuComercial entity)
		{
			this.SendPropertyChanging();
			entity.Proprietate = this;
		}
		
		private void detach_SpatiuComercials(SpatiuComercial entity)
		{
			this.SendPropertyChanging();
			entity.Proprietate = null;
		}
		
		private void attach_Terens(Teren entity)
		{
			this.SendPropertyChanging();
			entity.Proprietate = this;
		}
		
		private void detach_Terens(Teren entity)
		{
			this.SendPropertyChanging();
			entity.Proprietate = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SpatiuComercial")]
	public partial class SpatiuComercial : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SpatiuID;
		
		private System.Nullable<int> _ProprietateID;
		
		private string _StadiuConstructie;
		
		private string _TipSpatiu;
		
		private EntityRef<Proprietate> _Proprietate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSpatiuIDChanging(int value);
    partial void OnSpatiuIDChanged();
    partial void OnProprietateIDChanging(System.Nullable<int> value);
    partial void OnProprietateIDChanged();
    partial void OnStadiuConstructieChanging(string value);
    partial void OnStadiuConstructieChanged();
    partial void OnTipSpatiuChanging(string value);
    partial void OnTipSpatiuChanged();
    #endregion
		
		public SpatiuComercial()
		{
			this._Proprietate = default(EntityRef<Proprietate>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpatiuID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SpatiuID
		{
			get
			{
				return this._SpatiuID;
			}
			set
			{
				if ((this._SpatiuID != value))
				{
					this.OnSpatiuIDChanging(value);
					this.SendPropertyChanging();
					this._SpatiuID = value;
					this.SendPropertyChanged("SpatiuID");
					this.OnSpatiuIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProprietateID", DbType="Int")]
		public System.Nullable<int> ProprietateID
		{
			get
			{
				return this._ProprietateID;
			}
			set
			{
				if ((this._ProprietateID != value))
				{
					if (this._Proprietate.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProprietateIDChanging(value);
					this.SendPropertyChanging();
					this._ProprietateID = value;
					this.SendPropertyChanged("ProprietateID");
					this.OnProprietateIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StadiuConstructie", DbType="VarChar(20)")]
		public string StadiuConstructie
		{
			get
			{
				return this._StadiuConstructie;
			}
			set
			{
				if ((this._StadiuConstructie != value))
				{
					this.OnStadiuConstructieChanging(value);
					this.SendPropertyChanging();
					this._StadiuConstructie = value;
					this.SendPropertyChanged("StadiuConstructie");
					this.OnStadiuConstructieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipSpatiu", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string TipSpatiu
		{
			get
			{
				return this._TipSpatiu;
			}
			set
			{
				if ((this._TipSpatiu != value))
				{
					this.OnTipSpatiuChanging(value);
					this.SendPropertyChanging();
					this._TipSpatiu = value;
					this.SendPropertyChanged("TipSpatiu");
					this.OnTipSpatiuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proprietate_SpatiuComercial", Storage="_Proprietate", ThisKey="ProprietateID", OtherKey="ProprietateID", IsForeignKey=true, DeleteRule="CASCADE")]
		public Proprietate Proprietate
		{
			get
			{
				return this._Proprietate.Entity;
			}
			set
			{
				Proprietate previousValue = this._Proprietate.Entity;
				if (((previousValue != value) 
							|| (this._Proprietate.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Proprietate.Entity = null;
						previousValue.SpatiuComercials.Remove(this);
					}
					this._Proprietate.Entity = value;
					if ((value != null))
					{
						value.SpatiuComercials.Add(this);
						this._ProprietateID = value.ProprietateID;
					}
					else
					{
						this._ProprietateID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Proprietate");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Teren")]
	public partial class Teren : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TerenID;
		
		private System.Nullable<int> _ProprietateID;
		
		private string _TipTeren;
		
		private System.Nullable<bool> _Gaz;
		
		private System.Nullable<bool> _Electricitate;
		
		private System.Nullable<bool> _Apa;
		
		private System.Nullable<bool> _Canalizare;
		
		private EntityRef<Proprietate> _Proprietate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTerenIDChanging(int value);
    partial void OnTerenIDChanged();
    partial void OnProprietateIDChanging(System.Nullable<int> value);
    partial void OnProprietateIDChanged();
    partial void OnTipTerenChanging(string value);
    partial void OnTipTerenChanged();
    partial void OnGazChanging(System.Nullable<bool> value);
    partial void OnGazChanged();
    partial void OnElectricitateChanging(System.Nullable<bool> value);
    partial void OnElectricitateChanged();
    partial void OnApaChanging(System.Nullable<bool> value);
    partial void OnApaChanged();
    partial void OnCanalizareChanging(System.Nullable<bool> value);
    partial void OnCanalizareChanged();
    #endregion
		
		public Teren()
		{
			this._Proprietate = default(EntityRef<Proprietate>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TerenID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TerenID
		{
			get
			{
				return this._TerenID;
			}
			set
			{
				if ((this._TerenID != value))
				{
					this.OnTerenIDChanging(value);
					this.SendPropertyChanging();
					this._TerenID = value;
					this.SendPropertyChanged("TerenID");
					this.OnTerenIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProprietateID", DbType="Int")]
		public System.Nullable<int> ProprietateID
		{
			get
			{
				return this._ProprietateID;
			}
			set
			{
				if ((this._ProprietateID != value))
				{
					if (this._Proprietate.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProprietateIDChanging(value);
					this.SendPropertyChanging();
					this._ProprietateID = value;
					this.SendPropertyChanged("ProprietateID");
					this.OnProprietateIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipTeren", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string TipTeren
		{
			get
			{
				return this._TipTeren;
			}
			set
			{
				if ((this._TipTeren != value))
				{
					this.OnTipTerenChanging(value);
					this.SendPropertyChanging();
					this._TipTeren = value;
					this.SendPropertyChanged("TipTeren");
					this.OnTipTerenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gaz", DbType="Bit")]
		public System.Nullable<bool> Gaz
		{
			get
			{
				return this._Gaz;
			}
			set
			{
				if ((this._Gaz != value))
				{
					this.OnGazChanging(value);
					this.SendPropertyChanging();
					this._Gaz = value;
					this.SendPropertyChanged("Gaz");
					this.OnGazChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Electricitate", DbType="Bit")]
		public System.Nullable<bool> Electricitate
		{
			get
			{
				return this._Electricitate;
			}
			set
			{
				if ((this._Electricitate != value))
				{
					this.OnElectricitateChanging(value);
					this.SendPropertyChanging();
					this._Electricitate = value;
					this.SendPropertyChanged("Electricitate");
					this.OnElectricitateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apa", DbType="Bit")]
		public System.Nullable<bool> Apa
		{
			get
			{
				return this._Apa;
			}
			set
			{
				if ((this._Apa != value))
				{
					this.OnApaChanging(value);
					this.SendPropertyChanging();
					this._Apa = value;
					this.SendPropertyChanged("Apa");
					this.OnApaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Canalizare", DbType="Bit")]
		public System.Nullable<bool> Canalizare
		{
			get
			{
				return this._Canalizare;
			}
			set
			{
				if ((this._Canalizare != value))
				{
					this.OnCanalizareChanging(value);
					this.SendPropertyChanging();
					this._Canalizare = value;
					this.SendPropertyChanged("Canalizare");
					this.OnCanalizareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proprietate_Teren", Storage="_Proprietate", ThisKey="ProprietateID", OtherKey="ProprietateID", IsForeignKey=true, DeleteRule="CASCADE")]
		public Proprietate Proprietate
		{
			get
			{
				return this._Proprietate.Entity;
			}
			set
			{
				Proprietate previousValue = this._Proprietate.Entity;
				if (((previousValue != value) 
							|| (this._Proprietate.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Proprietate.Entity = null;
						previousValue.Terens.Remove(this);
					}
					this._Proprietate.Entity = value;
					if ((value != null))
					{
						value.Terens.Add(this);
						this._ProprietateID = value.ProprietateID;
					}
					else
					{
						this._ProprietateID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Proprietate");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserID;
		
		private string _UserType;
		
		private string _Username;
		
		private string _PasswordHashed;
		
		private string _Email;
		
		private string _Nume;
		
		private string _Prenume;
		
		private string _NrTelefon;
		
		private System.Nullable<bool> _isActive;
		
		private System.Nullable<System.DateTime> _DataCreare;
		
		private EntitySet<Privat> _Privats;
		
		private EntitySet<Agent> _Agents;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnUserTypeChanging(string value);
    partial void OnUserTypeChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordHashedChanging(string value);
    partial void OnPasswordHashedChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnNumeChanging(string value);
    partial void OnNumeChanged();
    partial void OnPrenumeChanging(string value);
    partial void OnPrenumeChanged();
    partial void OnNrTelefonChanging(string value);
    partial void OnNrTelefonChanged();
    partial void OnisActiveChanging(System.Nullable<bool> value);
    partial void OnisActiveChanged();
    partial void OnDataCreareChanging(System.Nullable<System.DateTime> value);
    partial void OnDataCreareChanged();
    #endregion
		
		public User()
		{
			this._Privats = new EntitySet<Privat>(new Action<Privat>(this.attach_Privats), new Action<Privat>(this.detach_Privats));
			this._Agents = new EntitySet<Agent>(new Action<Agent>(this.attach_Agents), new Action<Agent>(this.detach_Agents));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserType", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string UserType
		{
			get
			{
				return this._UserType;
			}
			set
			{
				if ((this._UserType != value))
				{
					this.OnUserTypeChanging(value);
					this.SendPropertyChanging();
					this._UserType = value;
					this.SendPropertyChanged("UserType");
					this.OnUserTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(100)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordHashed", DbType="NVarChar(300)")]
		public string PasswordHashed
		{
			get
			{
				return this._PasswordHashed;
			}
			set
			{
				if ((this._PasswordHashed != value))
				{
					this.OnPasswordHashedChanging(value);
					this.SendPropertyChanging();
					this._PasswordHashed = value;
					this.SendPropertyChanged("PasswordHashed");
					this.OnPasswordHashedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(300)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nume", DbType="NVarChar(100)")]
		public string Nume
		{
			get
			{
				return this._Nume;
			}
			set
			{
				if ((this._Nume != value))
				{
					this.OnNumeChanging(value);
					this.SendPropertyChanging();
					this._Nume = value;
					this.SendPropertyChanged("Nume");
					this.OnNumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenume", DbType="NVarChar(100)")]
		public string Prenume
		{
			get
			{
				return this._Prenume;
			}
			set
			{
				if ((this._Prenume != value))
				{
					this.OnPrenumeChanging(value);
					this.SendPropertyChanging();
					this._Prenume = value;
					this.SendPropertyChanged("Prenume");
					this.OnPrenumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NrTelefon", DbType="NVarChar(15)")]
		public string NrTelefon
		{
			get
			{
				return this._NrTelefon;
			}
			set
			{
				if ((this._NrTelefon != value))
				{
					this.OnNrTelefonChanging(value);
					this.SendPropertyChanging();
					this._NrTelefon = value;
					this.SendPropertyChanged("NrTelefon");
					this.OnNrTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isActive", DbType="Bit")]
		public System.Nullable<bool> isActive
		{
			get
			{
				return this._isActive;
			}
			set
			{
				if ((this._isActive != value))
				{
					this.OnisActiveChanging(value);
					this.SendPropertyChanging();
					this._isActive = value;
					this.SendPropertyChanged("isActive");
					this.OnisActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataCreare", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataCreare
		{
			get
			{
				return this._DataCreare;
			}
			set
			{
				if ((this._DataCreare != value))
				{
					this.OnDataCreareChanging(value);
					this.SendPropertyChanging();
					this._DataCreare = value;
					this.SendPropertyChanged("DataCreare");
					this.OnDataCreareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Privat", Storage="_Privats", ThisKey="UserID", OtherKey="UserID")]
		public EntitySet<Privat> Privats
		{
			get
			{
				return this._Privats;
			}
			set
			{
				this._Privats.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Agent", Storage="_Agents", ThisKey="UserID", OtherKey="UserID")]
		public EntitySet<Agent> Agents
		{
			get
			{
				return this._Agents;
			}
			set
			{
				this._Agents.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Privats(Privat entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_Privats(Privat entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
		
		private void attach_Agents(Agent entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_Agents(Agent entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Judete")]
	public partial class Judete : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _JudetID;
		
		private string _Denumire;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnJudetIDChanging(int value);
    partial void OnJudetIDChanged();
    partial void OnDenumireChanging(string value);
    partial void OnDenumireChanged();
    #endregion
		
		public Judete()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JudetID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int JudetID
		{
			get
			{
				return this._JudetID;
			}
			set
			{
				if ((this._JudetID != value))
				{
					this.OnJudetIDChanging(value);
					this.SendPropertyChanging();
					this._JudetID = value;
					this.SendPropertyChanged("JudetID");
					this.OnJudetIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Denumire", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Denumire
		{
			get
			{
				return this._Denumire;
			}
			set
			{
				if ((this._Denumire != value))
				{
					this.OnDenumireChanging(value);
					this.SendPropertyChanging();
					this._Denumire = value;
					this.SendPropertyChanged("Denumire");
					this.OnDenumireChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Privat")]
	public partial class Privat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PrivatID;
		
		private System.Nullable<int> _UserID;
		
		private EntitySet<Anunturi_vizualizate> _Anunturi_vizualizates;
		
		private EntitySet<LegaturaPrivatAgent> _LegaturaPrivatAgents;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPrivatIDChanging(int value);
    partial void OnPrivatIDChanged();
    partial void OnUserIDChanging(System.Nullable<int> value);
    partial void OnUserIDChanged();
    #endregion
		
		public Privat()
		{
			this._Anunturi_vizualizates = new EntitySet<Anunturi_vizualizate>(new Action<Anunturi_vizualizate>(this.attach_Anunturi_vizualizates), new Action<Anunturi_vizualizate>(this.detach_Anunturi_vizualizates));
			this._LegaturaPrivatAgents = new EntitySet<LegaturaPrivatAgent>(new Action<LegaturaPrivatAgent>(this.attach_LegaturaPrivatAgents), new Action<LegaturaPrivatAgent>(this.detach_LegaturaPrivatAgents));
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrivatID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PrivatID
		{
			get
			{
				return this._PrivatID;
			}
			set
			{
				if ((this._PrivatID != value))
				{
					this.OnPrivatIDChanging(value);
					this.SendPropertyChanging();
					this._PrivatID = value;
					this.SendPropertyChanged("PrivatID");
					this.OnPrivatIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int")]
		public System.Nullable<int> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Privat_Anunturi_vizualizate", Storage="_Anunturi_vizualizates", ThisKey="PrivatID", OtherKey="UtilizatorID")]
		public EntitySet<Anunturi_vizualizate> Anunturi_vizualizates
		{
			get
			{
				return this._Anunturi_vizualizates;
			}
			set
			{
				this._Anunturi_vizualizates.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Privat_LegaturaPrivatAgent", Storage="_LegaturaPrivatAgents", ThisKey="PrivatID", OtherKey="PrivatID")]
		public EntitySet<LegaturaPrivatAgent> LegaturaPrivatAgents
		{
			get
			{
				return this._LegaturaPrivatAgents;
			}
			set
			{
				this._LegaturaPrivatAgents.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Privat", Storage="_User", ThisKey="UserID", OtherKey="UserID", IsForeignKey=true, DeleteRule="CASCADE")]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.Privats.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.Privats.Add(this);
						this._UserID = value.UserID;
					}
					else
					{
						this._UserID = default(Nullable<int>);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Anunturi_vizualizates(Anunturi_vizualizate entity)
		{
			this.SendPropertyChanging();
			entity.Privat = this;
		}
		
		private void detach_Anunturi_vizualizates(Anunturi_vizualizate entity)
		{
			this.SendPropertyChanging();
			entity.Privat = null;
		}
		
		private void attach_LegaturaPrivatAgents(LegaturaPrivatAgent entity)
		{
			this.SendPropertyChanging();
			entity.Privat = this;
		}
		
		private void detach_LegaturaPrivatAgents(LegaturaPrivatAgent entity)
		{
			this.SendPropertyChanging();
			entity.Privat = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Agent")]
	public partial class Agent : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AgentID;
		
		private System.Nullable<int> _UserID;
		
		private string _NrLicenta;
		
		private string _NumeAgentie;
		
		private string _AdresaAgentie;
		
		private int _AniExperienta;
		
		private EntitySet<LegaturaPrivatAgent> _LegaturaPrivatAgents;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAgentIDChanging(int value);
    partial void OnAgentIDChanged();
    partial void OnUserIDChanging(System.Nullable<int> value);
    partial void OnUserIDChanged();
    partial void OnNrLicentaChanging(string value);
    partial void OnNrLicentaChanged();
    partial void OnNumeAgentieChanging(string value);
    partial void OnNumeAgentieChanged();
    partial void OnAdresaAgentieChanging(string value);
    partial void OnAdresaAgentieChanged();
    partial void OnAniExperientaChanging(int value);
    partial void OnAniExperientaChanged();
    #endregion
		
		public Agent()
		{
			this._LegaturaPrivatAgents = new EntitySet<LegaturaPrivatAgent>(new Action<LegaturaPrivatAgent>(this.attach_LegaturaPrivatAgents), new Action<LegaturaPrivatAgent>(this.detach_LegaturaPrivatAgents));
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgentID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int AgentID
		{
			get
			{
				return this._AgentID;
			}
			set
			{
				if ((this._AgentID != value))
				{
					this.OnAgentIDChanging(value);
					this.SendPropertyChanging();
					this._AgentID = value;
					this.SendPropertyChanged("AgentID");
					this.OnAgentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int")]
		public System.Nullable<int> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NrLicenta", DbType="VarChar(255)")]
		public string NrLicenta
		{
			get
			{
				return this._NrLicenta;
			}
			set
			{
				if ((this._NrLicenta != value))
				{
					this.OnNrLicentaChanging(value);
					this.SendPropertyChanging();
					this._NrLicenta = value;
					this.SendPropertyChanged("NrLicenta");
					this.OnNrLicentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeAgentie", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NumeAgentie
		{
			get
			{
				return this._NumeAgentie;
			}
			set
			{
				if ((this._NumeAgentie != value))
				{
					this.OnNumeAgentieChanging(value);
					this.SendPropertyChanging();
					this._NumeAgentie = value;
					this.SendPropertyChanged("NumeAgentie");
					this.OnNumeAgentieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdresaAgentie", DbType="VarChar(100)")]
		public string AdresaAgentie
		{
			get
			{
				return this._AdresaAgentie;
			}
			set
			{
				if ((this._AdresaAgentie != value))
				{
					this.OnAdresaAgentieChanging(value);
					this.SendPropertyChanging();
					this._AdresaAgentie = value;
					this.SendPropertyChanged("AdresaAgentie");
					this.OnAdresaAgentieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AniExperienta", DbType="Int NOT NULL")]
		public int AniExperienta
		{
			get
			{
				return this._AniExperienta;
			}
			set
			{
				if ((this._AniExperienta != value))
				{
					this.OnAniExperientaChanging(value);
					this.SendPropertyChanging();
					this._AniExperienta = value;
					this.SendPropertyChanged("AniExperienta");
					this.OnAniExperientaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Agent_LegaturaPrivatAgent", Storage="_LegaturaPrivatAgents", ThisKey="AgentID", OtherKey="AgentID")]
		public EntitySet<LegaturaPrivatAgent> LegaturaPrivatAgents
		{
			get
			{
				return this._LegaturaPrivatAgents;
			}
			set
			{
				this._LegaturaPrivatAgents.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Agent", Storage="_User", ThisKey="UserID", OtherKey="UserID", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.Agents.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.Agents.Add(this);
						this._UserID = value.UserID;
					}
					else
					{
						this._UserID = default(Nullable<int>);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LegaturaPrivatAgents(LegaturaPrivatAgent entity)
		{
			this.SendPropertyChanging();
			entity.Agent = this;
		}
		
		private void detach_LegaturaPrivatAgents(LegaturaPrivatAgent entity)
		{
			this.SendPropertyChanging();
			entity.Agent = null;
		}
	}
}
#pragma warning restore 1591
